services:
  - name: django-app
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVICE_TYPE
        value: web

  - name: celery-worker
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVICE_TYPE
        value: worker

  - name: celery-beat
    type: web
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SERVICE_TYPE
        value: beat

  - name: redis
    type: keyvalue
    plan: free
