services:
  - type: web
    name: django-app
    env: docker
    dockerfilePath: Dockerfile

  - type: worker
    name: celery-worker
    env: docker
    dockerfilePath: Dockerfile.worker

  - type: worker
    name: celery-beat
    env: docker
    dockerfilePath: Dockerfile.beat

  - type: redis
    name: redis
    plan: free
    ipAllowList: []
